name: Staging CD workflow
on:
  push:
    branches:
      - staging

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Copy ssh-key
        run: |
          mkdir -p ~/.ssh
          echo "${{secrets.SSH_PRIVATE_KEY}}" > ~/.ssh/id_rsa
          ssh-keyscan -H sitedoctruyen.id.vn > ~/.ssh/known_hosts
          chmod 600 ~/.ssh/id_rsa
          chmod 644 ~/.ssh/known_hosts
      - name: Stop app
        run: |
          ssh -i ~/.ssh/id_rsa triuq@sitedoctruyen.id.vn << 'EOF'
          pm2 stop doctruyen-be || true
          rm -rf ~/doctruyen/be
          mkdir -p ~/doctruyen/be
          EOF
      - name: compress the project
        run: |
          mkdir /tmp/snapshot
          cp -r . /tmp/snapshot
          tar -czf be.tar.gz -C /tmp/snapshot .

      - name: Copy and deploy in remote server
        run: |
          scp -i ~/.ssh/id_rsa -r be.tar.gz triuq@sitedoctruyen.id.vn:~/doctruyen/be
          ssh -i ~/.ssh/id_rsa triuq@sitedoctruyen.id.vn << 'EOF'
          cd ~/doctruyen/be
          tar -xzf be.tar.gz
          rm -rf be.tar.gz
          npm install
          pm2 start server.js --name doctruyen-be
          EOF
